version: "3.9"

services:
  openquerybi:
    build: ./servers/OpenQueryBI
    container_name: openquerybi
    restart: always
    volumes:
      - ./servers/OpenQueryBI:/app
    ports:
      - "8001:8001"
      - "8002:8002"

  hostclient:
    build: ./client
    container_name: hostclient
    restart: always
    volumes:
      - ./client/:/app
    ports:
      - "8501:8501"
    # command: >
    #   streamlit run app.py